package com.sqlite.realm.db;

import io.realm.RealmObject;

public class RealmDB extends RealmObject {

    private int id;
    private String name;

    // Standard getters & setters generated by your IDE…
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
